spring:
  redis:
    host: localhost
    port: 6379
    password:
  application:
    name: request-limit-aop

server:
  port: 8001
  servlet:
    context-path: /api/request-limit
request-limit: #限流配置
  scan-package: com/cn/lucky/morning/limit/controller/ #扫描注解包路径
